[project]
name = "tinylm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kaushik Sinha", email = "inftloop@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
tinylm = "tinylm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
